/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Refaccionaria;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class PanelFondo extends javax.swing.JPanel {
    
    
    public ImageIcon icono;
    /**
     * Creates new form PanelFondo
     */
    public PanelFondo() {
        initComponents();
    }

    public PanelFondo(int ancho, int alto) {
        this.setSize(ancho, alto);
        initComponents();
    }

    public void paintComponent(Graphics g){
        Dimension tam=getSize();
        icono=new ImageIcon(getClass().getResource("/imagenes/audiS5.jpg"));
        g.drawImage(icono.getImage(), 0, 0, tam.width,tam.height,null);
        setOpaque(false);        
        super.paintComponent(g);        
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
